backend:
  name: git-gateway
  branch: main  # Change this if your main branch has a different name

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "status"
    label: "Stock Status"
    folder: "content/status"
    create: true
    fields:
      - { label: "Status", name: "stock", widget: "select", options: ["In Stock", "Out of Stock"] }
